### ISSUE TITLE
Error: ENOENT, No such file or directory

### ISSUE THREAD

**Issue by humblewizard** [fivdi/mcp-spi-adc#11]
I'm trying to get the MCP3008 to work on my Raspberry Pi 4. I'm getting a fatal error as below. Any ideas?

/home/pi/webserver.js:152
    if (err) throw err;
             ^
Error: ENOENT, No such file or directory

Line 152 is in this bit of code:

```
const mcpadc = require('mcp-spi-adc');

const tempSensor = mcpadc.open(5, {speedHz: 20000}, err => {
    if (err) throw err;
```

The installation of the package went like this:

```
npm install mcp-spi-adc
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN pi@1.0.0 No repository field.

+ mcp-spi-adc@3.1.0
updated 1 package and audited 140 packages in 2.536s
```

**Comment by fivdi** [comment]
As mentioned in the [Installation](https://github.com/fivdi/mcp-spi-adc#installation) section of the readme, SPI needs to be enabled with the raspi-config tool on the Raspberry Pi before SPI can be used. It looks like SPI hasn't been enabled.

To enable SPI, run the raspi-config tool from the command line with the following command:
```
sudo raspi-config
```
Navigate to "5 Interfacing Options >> P4 SPI" and answer the question "Would you like the SPI interface to be enabled?" with Yes.

Depending on the version of Raspberry Pi OS (previously called Raspbian) being used, the Pi may need a reboot for the change to take effect.

Please give this a try to see if it resolves the issue.

**Comment by humblewizard** [comment]
Thanks for the reply Brian. Yes I did read that and I did use raspi-config
to enable the SPI connections. I did reboot afterwards and the results are
as I posted. So, I opened the config.txt file to confirm that SPI was
enabled and I found this:

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
dtparam=spi=on

So, I don't think that is the problem.

**Comment by fivdi** [comment]
Please post the following information:

- The output of the command `whoami`
- The output of the command `groups`
- The output of the command `uname -a`
- The output of the command `ls -l /dev/spi*`
- The complete contents of the file `/boot/config.txt`
- A short but complete program that can be used to reproduce the error.

**Comment by humblewizard** [comment]
Brian, thanks for having a look at this for me. Here are the things you
asked for:

whoampi: pi

groups: pi adm dialout cdrom sudo audio video plugdev games users input
netdev gpio i2c spi

uname: Linux raspberrypi 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020
armv7l GNU/Linux

ls: cannot access '/dev/spi*': No such file or directory

program having error =>

const mcpadc = require('mcp-spi-adc');

const tempSensor = mcpadc.open(5, {speedHz: 20000}, err => {
    if (err) throw err;

    setInterval(_ => {
        tempSensor.read((err, reading) => {
            if (err) throw err;

            console.log((reading.value * 3.3 - 0.5) * 100);
        });
    }, 1000);
});



/boot/config.txt =>

# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

#next has been added to get the serial temp sensor interface to run
dtoverlay=w1-gpio,gpiopin=4
dtoverlay=w1-gpio,gpiopin=5
dtoverlay=w1-gpio,gpiopin=6
dtoverlay=w1-gpio,gpiopin=7
#gpiopin=<x> if is different than 4. Default is 4.

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if
console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size
minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work
in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking,
or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d

**Comment by fivdi** [comment]
If the following line is removed from `/boot/config.txt` I would expect SPI to function correctly:
```
dtoverlay=w1-gpio,gpiopin=7
```
If SPI is configured using the following line in `/boot/config.txt`
```
dtparam=spi=on
```
then SPI expects to be able to use GPIO7, GPIO8, GPIO9, GPIO10 and GPIO11.

There is a conflict situation here. Both w1-gpio and SPI want to reserve GPIO7 for exclusive usage, so only one of them will get it. Running the command `dmesg` on your system should display error messages related to the conflict.

Alternatively, if you only want to connect 1 device to the SPI bus, replacing this line in `/boot/config.txt`:
```
dtparam=spi=on
```
with this line:
```
dtoverlay=spi0-1cs
```
should also resolve the issue.

**Comment by humblewizard** [comment]
Since I have serial temperature sensors one pin 7 I used the
"dtoverlay=spi0-1cs 1cs" suggestion. I've got a working A/D apparently, its
reporting data. Thanks for your help Brian.

**Comment by fivdi** [comment]
>  Thanks for your help Brian.

You're welcome.
