### ISSUE TITLE
bindings.js: 202 Uncaught TypeError: exists is not a function

### ISSUE THREAD

**Issue by IvanSemin33** [fivdi/mcp-spi-adc#14]
![image](https://user-images.githubusercontent.com/43711141/108359886-99744600-7201-11eb-8ef8-ea5b29d518d9.png)

I'm trying to use this lib with webpack or react and got this error.

Node: `v14.0.0`
NPM: `v6.14.4 `

**Comment by fivdi** [comment]
As mentioned in the [readme](https://github.com/fivdi/mcp-spi-adc#mcp-spi-adc), mcp-spi-adc is designed for usage from Node.js. It's not suitable for usage in a browser.

**Comment by fivdi** [comment]
I'll go ahead and close this as there is not TODO for mcp-spi-adc.
